### ISSUE TITLE
`safe_load` interface does not match `load` and `load_file` interface

### ISSUE THREAD

**Issue by sorryeh** [ruby/psych#354]
Hey folks! 👋 

I'm curious to know why: [safe_load's](https://github.com/ruby/psych/blob/master/lib/psych.rb#L349) interface does not match [load's](https://github.com/ruby/psych/blob/master/lib/psych.rb#L262) or [load_file's](https://github.com/ruby/psych/blob/master/lib/psych.rb#L514) interfaces?

```ruby
  def self.load_file filename, fallback: false
```

```ruby
  def self.load yaml, filename = nil, fallback: false, symbolize_names: false
```

```ruby
  def self.safe_load yaml, whitelist_classes = [], whitelist_symbols = [], aliases = false, filename = nil, symbolize_names: false
```

Why is fallback not available in the `safe_load` parameters?

I'll link a PR here, feel free to let me know why it isn't included or shouldn't be included.

Cheers!

**Comment by stomar** [comment]
It goes beyond mere differences in method signatures. For instance, currently the `fallback` option is only working properly for `Psych.load_file`, not for `Psych.load`, see PR #346. (Actually, unifying the method options was already on my agenda, but I didn't want to start that before the PR is commented upon.)

My understanding is that the differences are incidental and are caused by independent changes due to pull requests that only targeted a specific method, due to the personal need of the PR author, and related accidental design choices, that led to technical problems with adding some of the options to some of the other methods. Specifically, the use of both optional positional arguments and keyword arguments is problematic. (It caused e.g. issues when `symbolize_names` was added, see explanation in #337.)

In my opinion (as a minor contributor) the signatures should essentially be the same.

**Comment by sorryeh** [comment]
#358 Shipped, this is fixed for now.
