### ISSUE TITLE
Add safe_load_stream

### ISSUE THREAD

**Issue by kke** [ruby/psych#381]
There seems to be no `safe_load` equivalent for multi document yamls, such as `safe_load_stream`.

**Comment by sorryeh** [comment]
I'll look at adding this. I have the work half done on a local branch on my machine :grin:

**Comment by kke** [comment]
I made a small [gem](https://rubygems.org/gems/yaml-safe_load_stream) for this but it's not very full featured.

**Comment by hsbt** [comment]
I didn't have any opinion about this feature. and no one submit pull-request over four years.

**Comment by jlmuir** [comment]
@kke, I'd love to have a `safe_load_stream` method.  hsbt closed this as not planned with the reason that no one submitted a PR.  Since you wrote a separate gem providing `safe_load_stream`, would you be willing to submit a PR to add the method directly to Psych so that a separate gem is not needed?
