### ISSUE TITLE
Cannot install psych-3.1.0-java.gem

### ISSUE THREAD

**Issue by aboltart** [ruby/psych#427]
gem install psych
Fetching: psych-3.1.0-java.gem (100%)
  jar dependencies for psych-3.1.0-java.gemspec . . .
Dec 18, 2019 4:45:23 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://rubygems-proxy.torquebox.org:80: Connection reset
Dec 18, 2019 4:45:23 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://rubygems-proxy.torquebox.org:80
Dec 18, 2019 4:48:20 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://rubygems-proxy.torquebox.org:80: Connection reset
Dec 18, 2019 4:48:20 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute

**Comment by aboltart** [comment]
(Temporary?) workaround https://github.com/torquebox/jruby-maven-plugins/issues/100#issuecomment-567108219

**Comment by mohamedhafez** [comment]
rubygems-proxy.torquebox.org is running again so installing psych will work now, but its pretty scary that rubygems-proxy.torquebox.org is [unmaintained](https://github.com/jruby-gradle/jruby-gradle-plugin/issues/349#issuecomment-496564438), and not served over SSL. I've raised an issue on the main JRuby repo asking that an officially maintained, secure version be hosted somewhere like at jruby.org, since default JRuby gems and functionality depend on it

**Comment by hsbt** [comment]
This is not the issue of psych.
