### ISSUE TITLE
safe_load + YAML with "ruby/object" symbolizing keys even without symbolize_names = true

### ISSUE THREAD

**Issue by sergiodj** [ruby/psych#540]
Hi,

I noticed this difference of behaviour because of a failure with https://github.com/dtao/safe_yaml/ when running against Ruby 3.0.  I haven't had the chance to test with Ruby 3.1, sorry.

Given the following script:

``` ruby
require 'psych'
require 'ostruct'

a = Psych.safe_load("--- !ruby/object:OpenStruct\ntable:\n  foo: bar\n", permitted_classes: [OpenStruct])
puts a.class
puts a.instance_variable_get(:@table)
```
You will notice that it behaves differently when running against Ruby 2.7 and 3.0.

* Ruby 2.7 output:

``` ruby
OpenStruct
{"foo"=>"bar"}
```

* Ruby 3.0 output:

``` ruby
OpenStruct
{:foo=>"bar"}
```

The key simbolization occurs even without using the `symbolize_names` option.  I did some debugging but couldn't really find what is causing this difference in behaviour.  I'm not a Ruby expert and TBH I don't know if this is a known change in 3.0 or an actual bug.

Thanks in advance.

**Comment by zverok** [comment]
The [relevant change](https://github.com/ruby/ostruct/commit/683c3d63e9fa5478e12d1fa0b09b3151f577cb57) is made in `OpenStruct`, actually. 

In Ruby 2.7, it [hasn't had](https://github.com/ruby/ruby/blob/v2_7_0/lib/ostruct.rb) a dedicated `#init_with` method, but [it has now](https://github.com/ruby/ruby/blob/master/lib/ostruct.rb#L447).

This method is used by `Psych` to instantiate classes. When it is not present, Psych just does `instance_variable_set`. The 3.0+ behavior is more right because without a "hack" of directly setting instance variable, OpenStruct always converts keys:
```ruby
OpenStruct.new('foo' => 'bar').instance_variable_get('@table')
# => {:foo=>"bar"} -- even on Ruby 2.7
```

**Comment by sergiodj** [comment]
@zverok Ah, thank you so much for the explanation.  It makes more sense, now.  And given that this is not a bug but rather a behaviour change (albeit undocumented, as far as I researched), I'm closing this issue.
